"""Item 2 registered controls 1 (poisons), generated from a real export. Both must give check = false:
  P-comm : check G G           (a matrix with itself: commutator exactly 2, criterion II must fail)
  P-seg  : check G' H, with G' = G widened by +-W on every real part (W = 2*max|entry| + 10, so the box
           contains matrices with tr^2/det in [0,4] -- e.g. real scalar multiples of the identity -- and crit1 must fail)"""
import json, os
from fractions import Fraction
import lean_gen as LG
REPO = LG.REPO
d = json.load(open(os.path.join(LG.EXP, "ts2_0_v2.json")))
G, H = d["G"], d["H"]
mx = max(abs(Fraction(v)) for i in range(2) for j in range(2) for part in ("re", "im") for v in G[i][j][part])
W = 2*mx + 10
Gw = [[{"re": [str(Fraction(G[i][j]["re"][0]) - W), str(Fraction(G[i][j]["re"][1]) + W)],
        "im": [str(Fraction(G[i][j]["im"][0]) - W), str(Fraction(G[i][j]["im"][1]) + W)]} for j in range(2)] for i in range(2)]
src = f"""/- AUTO-GENERATED by qsim/lean_gen_controls.py. Registered controls (PREREG_lean_certificate_arithmetic.md):
   the checker must be shown to return FALSE. Boxes from lean_export/ts2_0_v2.json. -/
import ZiglinCert.Boxes

namespace Certs.Controls

def G : MB := {LG.mb(G)}

def H : MB := {LG.mb(H)}

/-- the widened box (contains real multiples of the identity, whose tr²/det = 4 ∈ [0,4]) -/
def Gw : MB := {LG.mb(Gw)}

theorem real_pair_passes : check G H = true := by decide +kernel

/-- P-comm: a matrix with itself commutes, so criterion (II) must fail. -/
theorem poison_comm : check G G = false := by decide +kernel

/-- P-seg: the widened box reaches the real segment, so criterion (I) must fail. -/
theorem poison_seg : crit1 Gw = false := by decide +kernel

end Certs.Controls
"""
open(os.path.join(LG.OUT, "Controls.lean"), "w").write(src)
print("W =", float(W))
