"""Item 2: turn gate-passing exports (lean_export/<family>_<row>_<v1|v2>.json) into Lean certificate files
lean/ZiglinCert/ZiglinCert/Certs/<Name>.lean. Mechanical: each exact dyadic rational becomes a ℚ literal.
Each file states  check G H = true  (by decide +kernel)  and the resulting  CertConclusion G H."""
import json, os, sys
from fractions import Fraction
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXP = os.path.join(REPO, "lean_export")
OUT = os.path.join(REPO, "lean", "ZiglinCert", "ZiglinCert", "Certs")


def q(s):
    f = Fraction(s)
    return f"(({f.numerator} : ℚ) / {f.denominator})"


def qi(pair):
    return f"⟨{q(pair[0])}, {q(pair[1])}⟩"


def mb(B):
    ent = lambda e: f"⟨{qi(e['re'])}, {qi(e['im'])}⟩"
    return "![![" + ", ".join(ent(B[0][j]) for j in range(2)) + "], ![" + ", ".join(ent(B[1][j]) for j in range(2)) + "]]"


def name_of(fam, row, which):
    return f"{fam}_{row}_{which}"


def gen(fam, row, which):
    d = json.load(open(os.path.join(EXP, f"{fam}_{row}_{which}.json")))
    kerr = fam == "kerrctl"
    assert d["gate_bit_for_bit"] and d["readback"] and (d["certificate_ok"] or kerr), "gate not passed"
    n = name_of(fam, row, which)
    os.makedirs(OUT, exist_ok=True)
    src = f"""/- AUTO-GENERATED by qsim/lean_gen.py from lean_export/{n}.json. Do not edit.
   {fam} row {row}, {which} boxes (N = {d['N']}); words g = {d['g_word']}, h = {d['h_word']}.
   Export gate: bit-for-bit reproduction of the recorded certificate midrads, plus ball-in-rectangle read-back. -/
import ZiglinCert.Boxes

namespace Certs

def {n}_G : MB := {mb(d['G'])}

def {n}_H : MB := {mb(d['H'])}

{"" if not kerr else "/-- INTEGRABLE CONTROL (Kerr): the checker must REJECT. -/"}
theorem {n}_check : check {n}_G {n}_H = {"false" if kerr else "true"} := by decide +kernel
{"" if kerr else chr(10) + f"theorem {n} : CertConclusion {n}_G {n}_H := cert_of_check _ _ {n}_check" + chr(10)}
end Certs
"""
    fn = os.path.join(OUT, f"{n}.lean")
    open(fn, "w").write(src)
    return fn


if __name__ == "__main__":
    print(gen(sys.argv[1], int(sys.argv[2]), sys.argv[3]))
