"""Item 2: Lean-check every gate-passing export. For each: generate the certificate file, compile it with the kernel
(`decide +kernel`), and record the outcome and the printed axioms in lean_export/lean_results.json. Then refresh the
index module ZiglinCert/Certs/All.lean, which imports every kernel-checked certificate (for one final `lake build`)."""
import glob, json, os, re, subprocess, sys, time
import lean_gen as LG
REPO = LG.REPO
LEAN = os.path.join(REPO, "lean", "ZiglinCert")
RES = os.path.join(LG.EXP, "lean_results.json")
OK_AX = "[propext, Classical.choice, Quot.sound]"


def main():
    res = json.load(open(RES)) if os.path.exists(RES) else {}
    for fn in sorted(glob.glob(os.path.join(LG.EXP, "*_v[12].json"))):
        n = os.path.basename(fn)[:-5]
        fam, row, which = n.rsplit("_", 2)
        if fam == "kerrctl":
            continue
        d = json.load(open(fn))
        if not (d.get("gate_bit_for_bit") and d.get("certificate_ok") and d.get("readback")):
            res[n] = dict(status="export gate not passed")
            continue
        if res.get(n, {}).get("status") == "LEAN-CHECKED":
            continue
        LG.gen(fam, int(row), which)
        t0 = time.time()
        p = subprocess.run(["lake", "env", "lean", f"ZiglinCert/Certs/{n}.lean"], cwd=LEAN, capture_output=True, text=True,
                           timeout=7200)
        out = p.stdout + p.stderr
        m = re.search(rf"'Certs\.{n}' depends on axioms: (\[.*?\])", out)
        ax = m.group(1) if m else None
        ok = (p.returncode == 0 and ax == OK_AX and "error" not in out)
        res[n] = dict(status="LEAN-CHECKED" if ok else "not kernel-checked", axioms=ax, returncode=p.returncode,
                      seconds=round(time.time() - t0, 1), N=d["N"], words=[d["g_word"], d["h_word"]],
                      error=None if ok else out[-2000:])
        print(f"{n}: {res[n]['status']} [{res[n]['seconds']} s] axioms={ax}", flush=True)
        json.dump(res, open(RES, "w"), indent=1)
    checked = sorted(k for k, v in res.items() if v.get("status") == "LEAN-CHECKED")
    idx = "/- AUTO-GENERATED by qsim/lean_check_all.py: imports every kernel-checked certificate. -/\n" + \
          "".join(f"import ZiglinCert.Certs.{k}\n" for k in checked) + "import ZiglinCert.Certs.Controls\n" + \
          "".join(f"import ZiglinCert.Certs.{os.path.basename(k)[:-5]}\n" for k in sorted(glob.glob(os.path.join(LG.OUT, "kerrctl_*.lean"))))
    open(os.path.join(LG.OUT, "All.lean"), "w").write(idx)
    json.dump(res, open(RES, "w"), indent=1)
    print(f"{len(checked)} LEAN-CHECKED; index refreshed", flush=True)


if __name__ == "__main__":
    main()
