"""CAPD third replay of the Morales-Ramis certificates: generator + runner (ARB-FREE on the CAPD side).

Fields  -> C++ header (tests/gen/<tag>.h) for tests/replay_driver.cpp:
  * exact rational fields: p = Pp/Qp, q = Pq/Qq, polynomials in t and E_1..E_K, E_k = exp(w_k(t)), w_k = n_k/d_k;
  * coefficients are passed as exact dyadic enclosures (hex, computed here with Python integers -- no floating
    point, no Arb); the C++ side is CAPD MpInterval on MPFR only.
Loops   -> the certificate's own polylines (ia_hub.loop_points: the exact float vertices v1 and v2 transported).
Usage (dev):  mr_replay.py dev-mine <family> <row>    (fields from this repo's sympy code: ENGINEERING ONLY)
              mr_replay.py run <fields.json> <family> <row> [secondary]
"""
import json, os, subprocess, sys, time
from fractions import Fraction
from pathlib import Path

HERE = Path(__file__).resolve().parent
QSIM = HERE.parent
sys.path.insert(0, str(QSIM))
GEN = HERE / "tests" / "gen"
PREC = 256

# ----------------------------------------------------------------------------- exact rational -> dyadic enclosure
def enclose(fr, prec=PREC):
    """(lo_hex, hi_hex): exact prec-bit dyadics with lo <= fr <= hi (lo == hi iff fr is such a dyadic)."""
    fr = Fraction(fr)
    if fr == 0: return ("0x0p0", "0x0p0")
    neg = fr < 0; a = -fr if neg else fr
    n, d = a.numerator, a.denominator
    e = n.bit_length() - d.bit_length() - prec           # a / 2^e has about prec (+-1) bits
    def fl(e):
        return (n << -e) // d if e < 0 else n // (d << e)
    while fl(e) >= (1 << prec): e += 1
    while fl(e) < (1 << (prec - 1)): e -= 1
    lo = fl(e)
    exact = (lo * (d << e) == n) if e >= 0 else (lo * d == (n << -e))
    hi = lo if exact else lo + 1
    if neg: lo, hi = -hi, -lo
    h = lambda m: ("-" if m < 0 else "") + "0x%xp%d" % (abs(m), e)
    return (h(lo), h(hi))

def hexd(x):
    """exact hex of a Python float (an exact dyadic)"""
    m, e = float(x).as_integer_ratio()
    if m == 0: return "0x0p0"
    k = e.bit_length() - 1                                 # denominator is 2^k
    assert e == 1 << k
    return ("-" if m < 0 else "") + "0x%xp%d" % (abs(m), -k)

# ----------------------------------------------------------------------------- fields
def fields_mine(family, row):
    """This repo's own exact fields (sympy), for ENGINEERING runs only; the registered replay uses the bridge's."""
    import sympy as sp
    import lean_export as LE
    S, sing, cert, v1rec, N = LE.source(family, row)[:5]
    var = S["var"]
    def mon(expr):
        ex = sp.expand(expr)
        return {(int(sp.degree(m, var)),): Fraction(int(c.p), int(c.q))
                for c, m in [(t.as_coeff_Mul()) for t in sp.Add.make_args(ex)]} if True else None
    out = {}
    for nm in ("p", "q"):
        for part in ("P", "Q"):
            ex = sp.expand(S["to_expr"](S[nm], part))
            if ex.free_symbols - {var}:
                raise NotImplementedError("dev-mine supports pure rational fields only (TS); exp factors: use bridge export")
            poly = sp.Poly(ex, var)
            out[nm + part] = {(i,): Fraction(int(c.p), int(c.q)) for (i,), c in poly.terms()}
    return dict(var=str(var), exps=[], p={"num": out["pP"], "den": out["pQ"]}, q={"num": out["qP"], "den": out["qQ"]}), cert

# ----------------------------------------------------------------------------- C++ generation
def gen_header(F, tag):
    """F: dict(exps=[(numcoeffs, dencoeffs)], p={'num': {mon: Fraction}, 'den': ...}, q=...). mon = (i, j1..jK)."""
    K = len(F["exps"])
    coef = []                                              # exact Fractions, in parameter order
    def P(fr):
        coef.append(Fraction(fr)); return "par[%d]" % (4 + len(coef) - 1)
    L = []
    L.append("// GENERATED by qsim/capd/mr_replay.py for %s -- do not edit" % tag)
    L.append("#pragma once")
    L.append("#include <vector>")
    L.append("#define NE %d" % K)
    L.append("namespace replay_gen {")
    L.append("using capd::autodiff::Node;")
    L.append("struct CN { Node re, im; };")
    L.append("inline CN mul(const CN& a, const CN& b) { return {a.re * b.re - a.im * b.im, a.re * b.im + a.im * b.re}; }")
    L.append("inline CN add(const CN& a, const CN& b) { return {a.re + b.re, a.im + b.im}; }")
    L.append("inline CN neg(const CN& a) { return {-a.re, -a.im}; }")
    L.append("inline CN div(const CN& a, const CN& b) { Node d = b.re * b.re + b.im * b.im; "
             "return {(a.re * b.re + a.im * b.im) / d, (a.im * b.re - a.re * b.im) / d}; }")
    L.append("}")
    body = []
    body.append("  using namespace replay_gen;")
    body.append("  Node zero = s * 0.0;   // a zero node attached to this map's DAG")
    body.append("  CN dt = {par[2] - par[0], par[3] - par[1]};")
    body.append("  CN t = {par[0] + dt.re * s, par[1] + dt.im * s};")
    for k in range(K):
        body.append("  CN E%d = {in[%d], in[%d]};" % (k, 8 + 2 * k, 9 + 2 * k))
    cnt = [0]
    def tmp():
        cnt[0] += 1; return "v%d" % cnt[0]
    def horner(coeffs):
        """coeffs: dict deg -> Fraction (real). Returns a CN variable name."""
        degs = sorted(coeffs)
        if not degs: return None
        top = max(degs)
        acc = tmp(); body.append("  CN %s = {zero + %s, zero};" % (acc, P(coeffs[top])))
        for dgr in range(top - 1, -1, -1):
            nxt = tmp()
            c = coeffs.get(dgr)
            if c is None or c == 0:
                body.append("  CN %s = mul(%s, t);" % (nxt, acc))
            else:
                body.append("  CN %s = mul(%s, t); %s.re = %s.re + %s;" % (nxt, acc, nxt, nxt, P(c)))
            acc = nxt
        return acc
    def poly_tE(mons):
        groups = {}
        for mon, c in mons.items():
            if c == 0: continue
            groups.setdefault(tuple(mon[1:]), {})[mon[0]] = Fraction(c)
        total = None
        for eexp, coeffs in sorted(groups.items()):
            h = horner(coeffs)
            for k, j in enumerate(eexp):
                for _ in range(j):
                    nxt = tmp(); body.append("  CN %s = mul(%s, E%d);" % (nxt, h, k)); h = nxt
            if total is None: total = h
            else:
                nxt = tmp(); body.append("  CN %s = add(%s, %s);" % (nxt, total, h)); total = nxt
        if total is None:
            total = tmp(); body.append("  CN %s = {zero, zero};" % total)
        return total
    pN, pD = poly_tE(F["p"]["num"]), poly_tE(F["p"]["den"])
    qN, qD = poly_tE(F["q"]["num"]), poly_tE(F["q"]["den"])
    body.append("  CN pp = div(%s, %s), qq = div(%s, %s);" % (pN, pD, qN, qD))
    body.append("  CN r0[2] = {{in[0], in[1]}, {in[2], in[3]}}, r1[2] = {{in[4], in[5]}, {in[6], in[7]}};")
    body.append("  for (int j = 0; j < 2; ++j) {")
    body.append("    CN d0 = mul(dt, r1[j]);")
    body.append("    CN d1 = mul(dt, neg(add(mul(qq, r0[j]), mul(pp, r1[j]))));")
    body.append("    out[2 * j] = d0.re; out[2 * j + 1] = d0.im; out[4 + 2 * j] = d1.re; out[5 + 2 * j] = d1.im;")
    body.append("  }")
    # E_k' = dt * w_k'(t) * E_k,  w_k' = (n' d - n d') / d^2  (exact coefficient lists)
    wcoef_index = []
    for k, (num, den) in enumerate(F["exps"]):
        num = [Fraction(c) for c in num]; den = [Fraction(c) for c in den]
        dn = [i * num[i] for i in range(1, len(num))]; dd = [i * den[i] for i in range(1, len(den))]
        def pmul(a, b):
            r = [Fraction(0)] * (len(a) + len(b) - 1) if a and b else []
            for i, x in enumerate(a):
                for j, y in enumerate(b): r[i + j] += x * y
            return r
        def psub(a, b):
            n_ = max(len(a), len(b)); return [(a[i] if i < len(a) else 0) - (b[i] if i < len(b) else 0) for i in range(n_)]
        Nw = psub(pmul(dn, den), pmul(num, dd)); Dw = pmul(den, den)
        a = horner({i: c for i, c in enumerate(Nw) if c != 0}) or "CN{zero, zero}"
        b = horner({i: c for i, c in enumerate(Dw) if c != 0})
        body.append("  { CN de = mul(dt, mul(div(%s, %s), E%d)); out[%d] = de.re; out[%d] = de.im; }" % (a, b, k, 8 + 2 * k, 9 + 2 * k))
        # parameters for the point evaluation of w_k itself (driver's w_at)
        wcoef_index.append((len(coef), [P(c) for c in num], len(coef) - len(num), [P(c) for c in den], len(coef) - len(den)))
    fn = ["inline void field(capd::autodiff::Node s, capd::autodiff::Node in[], int, capd::autodiff::Node out[], int, "
          "capd::autodiff::Node par[], int) {"] + body + ["}"]
    # w_at: MPFR interval evaluation of w_k = n_k / d_k at a point (driver computes E = exp(w))
    W = ["inline void w_at(int k, const capd::MpInterval& tre, const capd::MpInterval& tim, "
         "const std::vector<capd::MpInterval>& C, capd::MpInterval& wre, capd::MpInterval& wim) {",
         "  using capd::MpInterval;",
         "  auto horn = [&](int first, int n, MpInterval& r, MpInterval& i) {",
         "    r = C[first + n - 1]; i = MpInterval(0);",
         "    for (int j = n - 2; j >= 0; --j) { MpInterval nr = r * tre - i * tim + C[first + j]; i = r * tim + i * tre; r = nr; }",
         "  };",
         "  MpInterval nr, ni, dr, di;"]
    for k, (_, numP, numFirst, denP, denFirst) in enumerate(wcoef_index):
        W.append("  if (k == %d) { horn(%d, %d, nr, ni); horn(%d, %d, dr, di); }" % (k, numFirst, len(numP), denFirst, len(denP)))
    W += ["  if (k < 0 || k >= NE) throw std::runtime_error(\"w_at: bad k\");",
          "  MpInterval d = dr * dr + di * di;",
          "  if (!capd_proof::certainly_positive(d)) throw std::runtime_error(\"w_at: denominator not certainly != 0\");",
          "  wre = (nr * dr + ni * di) / d; wim = (ni * dr - nr * di) / d;",
          "}"] if K else ["  (void)k; (void)tre; (void)tim; (void)C; (void)wre; (void)wim;", "}"]
    L.append("#define NPAR_COEF %d" % len(coef))
    src = "\n".join(L + fn + W) + "\n"
    return src, coef

def loop_vertices(geo, ngon=16, radius_scale=1.0):
    import ia_hub as IA
    z0 = complex(*geo["base"]); c = complex(*geo["center"]); r = geo["radius"] * radius_scale
    return IA.loop_points(z0, c, r, ngon=ngon)

def build_input(coef, cert, ngon=16, radius_scale=1.0, order=30):
    import ast   # the recorded geometry is a Python dict literal (str); literal_eval only, never eval
    geo = cert["geometry"] if isinstance(cert["geometry"], dict) else ast.literal_eval(cert["geometry"])
    names = sorted(set(cert["g"].split("*") + cert["h"].split("*")))
    lines = ["PREC %d" % PREC, "ORDER %d" % order]
    for i, c in enumerate(coef):
        lo, hi = enclose(c); lines.append("PAR %d %s %s" % (i, lo, hi))
    for n in names:
        vs = loop_vertices(geo[n], ngon, radius_scale)
        lines.append("LOOP %s %d" % (n, len(vs)))
        for z in vs: lines.append("V %s %s" % (hexd(z.real), hexd(z.imag)))
    lines.append("WORD g %s" % cert["g"]); lines.append("WORD h %s" % cert["h"]); lines.append("END")
    return "\n".join(lines) + "\n"

def compile_row(tag, header_src):
    GEN.mkdir(exist_ok=True)
    hp = GEN / (tag + ".h"); hp.write_text(header_src)
    exe = GEN / ("replay_" + tag)
    env = dict(os.environ)
    cmd = ["zsh", str(HERE / "tests" / "guard_build.sh"), str(HERE / "tests" / "replay_driver.cpp"), str(exe)]
    # the field header is selected by a macro; guard_build passes extra flags through CXXEXTRA
    env["CXXEXTRA"] = '-DREPLAY_FIELD="%s"' % hp
    r = subprocess.run(cmd, capture_output=True, text=True, env=env)
    ok = "BUILT" in r.stdout
    return ok, exe, (r.stdout + r.stderr)[-3000:]

if __name__ == "__main__":
    mode = sys.argv[1]
    if mode == "dev-mine":
        fam, row = sys.argv[2], int(sys.argv[3])
        F, cert = fields_mine(fam, row)
        tag = "dev_%s_%d" % (fam, row)
        src, coef = gen_header(F, tag)
        ok, exe, log = compile_row(tag, src)
        print("compile", ok); print(log if not ok else log[-400:])
        if ok:
            inp = build_input(coef, cert)
            (GEN / (tag + ".in")).write_text(inp)
            t0 = time.time()
            r = subprocess.run([str(exe)], input=inp, capture_output=True, text=True)
            (GEN / (tag + ".out")).write_text(r.stdout); print(r.stderr[-2000:])
            print("rc", r.returncode, "%.0fs" % (time.time() - t0)); print("\n".join(r.stdout.splitlines()[-24:]))
